---
- name: install and configure Jenkins
  hosts: # TBD
  become: yes
  become_user: root  
  roles:
     - users
     - patching 
     - packages
     -  docker
     - docker-compose
     - jenkins
     - reboot